"""create foundation tables

Revision ID: 0001_create_foundation_tables
Revises:
Create Date: 2026-07-17
"""
import sqlalchemy as sa

from alembic import op

revision = "0001_create_foundation_tables"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("projects", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(255), nullable=False), sa.Column("code", sa.String(64), nullable=False, unique=True), sa.Column("description", sa.Text()), sa.Column("bitrix_group_id", sa.Integer()), sa.Column("technical_user_id", sa.Integer()), sa.Column("numbering_prefix", sa.String(32)), sa.Column("is_active", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("employees", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("full_name", sa.String(255), nullable=False), sa.Column("last_name", sa.String(100)), sa.Column("first_name", sa.String(100)), sa.Column("middle_name", sa.String(100)), sa.Column("email", sa.String(255), unique=True), sa.Column("personnel_number", sa.String(64), unique=True), sa.Column("bitrix_user_id", sa.Integer()), sa.Column("source_system", sa.String(64)), sa.Column("is_active", sa.Boolean(), nullable=False), sa.Column("is_available_in_bitrix", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("directions", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("name", sa.String(255), nullable=False), sa.Column("code", sa.String(64), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False), sa.Column("sort_order", sa.Integer(), nullable=False))
    op.create_table("blocks", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("direction_id", sa.Integer(), sa.ForeignKey("directions.id", ondelete="CASCADE"), nullable=False), sa.Column("name", sa.String(255), nullable=False), sa.Column("code", sa.String(64), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False), sa.Column("sort_order", sa.Integer(), nullable=False))
    op.create_table("employee_aliases", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("employee_id", sa.Integer(), sa.ForeignKey("employees.id", ondelete="CASCADE"), nullable=False), sa.Column("alias", sa.String(255), nullable=False), sa.Column("normalized_alias", sa.String(255), nullable=False), sa.Column("source", sa.String(64)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_index("ix_employee_aliases_normalized_alias", "employee_aliases", ["normalized_alias"])
    op.create_table("employee_lists", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("name", sa.String(255), nullable=False), sa.Column("description", sa.Text()), sa.Column("is_active", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("employee_list_members", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("employee_list_id", sa.Integer(), sa.ForeignKey("employee_lists.id", ondelete="CASCADE"), nullable=False), sa.Column("employee_id", sa.Integer(), sa.ForeignKey("employees.id", ondelete="CASCADE"), nullable=False), sa.Column("sort_order", sa.Integer(), nullable=False), sa.UniqueConstraint("employee_list_id", "employee_id"))
    op.create_table("protocols", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id"), nullable=False), sa.Column("protocol_type", sa.String(64), nullable=False), sa.Column("title", sa.String(500), nullable=False), sa.Column("number", sa.String(64)), sa.Column("meeting_date", sa.Date()), sa.Column("status", sa.String(32), nullable=False), sa.Column("source_type", sa.String(32), nullable=False), sa.Column("source_filename", sa.String(255)), sa.Column("source_file_path", sa.String(500)), sa.Column("created_by", sa.String(255)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("protocol_sections", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("protocol_id", sa.Integer(), sa.ForeignKey("protocols.id", ondelete="CASCADE"), nullable=False), sa.Column("direction_id", sa.Integer(), sa.ForeignKey("directions.id")), sa.Column("block_id", sa.Integer(), sa.ForeignKey("blocks.id")), sa.Column("title", sa.String(500), nullable=False), sa.Column("sort_order", sa.Integer(), nullable=False), sa.Column("source_page", sa.Integer()), sa.Column("source_paragraph", sa.Integer()), sa.Column("source_table", sa.Integer()), sa.Column("original_text", sa.Text()))
    op.create_table("protocol_tasks", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("protocol_id", sa.Integer(), sa.ForeignKey("protocols.id", ondelete="CASCADE"), nullable=False), sa.Column("section_id", sa.Integer(), sa.ForeignKey("protocol_sections.id")), sa.Column("number", sa.String(64), nullable=False), sa.Column("title", sa.String(500), nullable=False), sa.Column("description", sa.Text()), sa.Column("acceptance_criteria", sa.Text()), sa.Column("deadline", sa.Date()), sa.Column("priority", sa.String(32)), sa.Column("create_as_subtasks", sa.Boolean(), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("original_text", sa.Text()), sa.Column("source_page", sa.Integer()), sa.Column("source_paragraph", sa.Integer()), sa.Column("source_table", sa.Integer()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("protocol_task_assignments", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("protocol_task_id", sa.Integer(), sa.ForeignKey("protocol_tasks.id", ondelete="CASCADE"), nullable=False), sa.Column("employee_id", sa.Integer(), sa.ForeignKey("employees.id")), sa.Column("source_employee_list_id", sa.Integer(), sa.ForeignKey("employee_lists.id")), sa.Column("individual_title", sa.String(500)), sa.Column("individual_description", sa.Text()), sa.Column("individual_acceptance_criteria", sa.Text()), sa.Column("individual_deadline", sa.Date()), sa.Column("individual_priority", sa.String(32)), sa.Column("sort_order", sa.Integer(), nullable=False))
    op.create_table("bitrix_task_links", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("protocol_task_id", sa.Integer(), sa.ForeignKey("protocol_tasks.id", ondelete="CASCADE"), nullable=False), sa.Column("assignment_id", sa.Integer(), sa.ForeignKey("protocol_task_assignments.id")), sa.Column("bitrix_task_id", sa.Integer()), sa.Column("parent_bitrix_task_id", sa.Integer()), sa.Column("task_type", sa.String(32), nullable=False), sa.Column("external_key", sa.String(255), nullable=False, unique=True), sa.Column("sync_status", sa.String(32), nullable=False), sa.Column("last_synced_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("task_assessments", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("protocol_task_id", sa.Integer(), sa.ForeignKey("protocol_tasks.id", ondelete="CASCADE"), nullable=False), sa.Column("provider", sa.String(64), nullable=False), sa.Column("model", sa.String(128)), sa.Column("prompt_version", sa.String(64), nullable=False), sa.Column("overall_score", sa.Integer()), sa.Column("clarity_score", sa.Integer()), sa.Column("completeness_score", sa.Integer()), sa.Column("smart_score", sa.Integer()), sa.Column("acceptance_criteria_score", sa.Integer()), sa.Column("summary", sa.Text()), sa.Column("missing_information_json", sa.Text()), sa.Column("warnings_json", sa.Text()), sa.Column("recommendations_json", sa.Text()), sa.Column("suggested_title", sa.String(500)), sa.Column("suggested_description", sa.Text()), sa.Column("suggested_acceptance_criteria", sa.Text()), sa.Column("raw_response_json", sa.Text()), sa.Column("created_by", sa.String(255)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()))


def downgrade() -> None:
    for table in ["task_assessments", "bitrix_task_links", "protocol_task_assignments", "protocol_tasks", "protocol_sections", "protocols", "employee_list_members", "employee_lists", "employee_aliases", "blocks", "directions", "employees", "projects"]:
        op.drop_table(table)
